### ISSUE TITLE
QUESTION: Possible to stream data instead of downloading and extracting the zip/h5p?

### ISSUE THREAD

**Issue by asif-ir** [tunapanda/h5p-standalone#108]
Is there any way to use this library if we can't pull and unzip the h5p bundle every time and instead we store unzipped data directly in some blob storage (like GCS) and provide url to that directory?

**Comment by kennberg** [comment]
H5P player loads the content files in the browser (client-side). If you were to point to .h5p file, which is a zip file, the browser wouldn't be able to access the files inside it. AFAIK you need to host the content files in GCS.

**Comment by mimidotsuser** [comment]
linking a related issue #16

From my theoretical standpoint, it is technically plausible. 

One approach you can try is using [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to intercept all H5P requests. The web worker would have to do all the good stuff like unzipping/reading any requested file. 

An H5P zipped file includes the instructions on what (_content type_) and how to display the content (_h5p.json & library definitions_). Thus, an H5P player acts as an execution engine and a glue to tie everything together.

If you're concerned about storage space, I would recommend storing all H5P libraries in a single location (to avoid duplicates).   _~~Most~~_ H5P libraries are versioned, so they are easily reused by different content types.

**Comment by wilsonatcollaboro** [comment]
@0xMurage  we have an exact same requirement here in our product.

The H5P file would be stored in blob storage (regardless Azure blob storage / S3 compatible ones). Ideally it would be extracted to individual files, so that it does not require extraction for every user access.

However, in order to protect the contents, we would need to add an access signature as a parameter to the url of the resource upon every user request, which will be complicated since the player is not aware of any parameters.

I had a look at the web worker, it seems it is able to intercept all requests. For the player, I believe it only uses `fetch`. As are we only interested in adding the access token as a parameter, we just need to intercept the requests to the blob storage and dynamically add the access parameter?

**Comment by 0xMurage** [comment]
> we only interested in adding the access token as a parameter, we just need to intercept the requests to the blob storage and dynamically add the access parameter?

@wilsonatcollaboro 

Yes, that is correct. The web worker would act as a proxy, but instead of pushing the requests upstream, you would serve browser-side extracted files.

Ideally, you would fetch the zipped file before initializing the player or after intercepting either the `h5p.json` or `content.json` file requests.



If your files upstream are already extracted, using web workers to add the headers/parameters to the request URL is currently the most straightforward solution.

**Comment by wilsonatcollaboro** [comment]
Hi @0xMurage  thanks for the insights.

One thing that I missed in the first question is: if the h5p file is extracted beforehand, then it should be more than `fetch` that should be intercepted, but also other places, like img "src" etc., right?

**Comment by 0xMurage** [comment]
> Hi [@0xMurage](https://github.com/0xMurage) thanks for the insights.
> 
> One thing that I missed in the first question is: if the h5p file is extracted beforehand, then it should be more than `fetch` that should be intercepted, but also other places, like img "src" etc., right?

Yes

**Comment by wilsonatcollaboro** [comment]
Roger that, thanks a lot for the clarification.
