### ISSUE TITLE
jQuery.Deferred exception: "prototype" is read-only

### ISSUE THREAD

**Issue by ghost** [tunapanda/h5p-standalone#119]
Hi,
It's been a few days that I'm having the following error in frame.bundle.js:
jQuery.Deferred exception: "prototype" is read-only
It happens with Interactive Books and Dialog Cards.
Any idea how to solve the same?

**Comment by eorhan** [comment]
Hi, 
I just changed the l.prototype variable to l.aaa in the frame.bundle.js file on the dialog cards. Unfortunately, frame.bundle.js of dialog cards and other modules are separate.

**Comment by murageyun** [comment]
@pevaristo, the easiest (not best) way to go around this issue is by removing all `"use strict;"` statements from `frame.bundle.js`

We hope the open PR #118  fixing this issue will be merged as soon as possible. 
You could also
 - clone this project 
 -  checkout  refactor/ts_migration branch 
 -  install dependencies  by running `yarn install` or `npm i`
 - compile/build  `yarn build`. Use the /dist output files which contain the fix.
