### ISSUE TITLE
How to POST the response from xAPI events to a local api

### ISSUE THREAD

**Issue by Mithlesh29** [tunapanda/h5p-standalone#128]
Can Anyone help me on how to POST my response from xAPI events to my local Api . 
I am able to get the values from my console.log . But I am unable to POST the values to my api . 

Script.js File

`
let response = await fetch('https://localhost:8000/api/institute/admin/category/<categoty-id>/h5p-question/ ', {
    method: 'POST',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({ "Question": value.object.definition.description , "Answers":value.object.definition.choices })
})
let result = await response.json();
alert(result.message);

`

**Comment by geirfp** [comment]
Please explain more about what error messages you are getting when trying to send the data. Is it by intention that you have double slashes in the URL? You can also debug by printing a serialization of the whole request you are going to send, in order to check that the composition of it is correct, and not just each small part. Good luck!
