### ISSUE TITLE
Example of Multiple Embeds

### ISSUE THREAD

**Issue by nbuonin** [tunapanda/h5p-standalone#26]
Could you add to the readme an example of embedding multiple h5p's on a single page?

Specifically, I'm confused about what the `id` attribute in the constructor does.  I've tried:
```
$('.h5p-container-1').h5p({
    id: 1,
    frameJs: '../dist/js/h5p-standalone-frame.min.js',
    frameCss: '../dist/styles/h5p.css',
    h5pContent: '../workspace/multiple-choice'
});
$('.h5p-container-2').h5p({
    id: 2,
    frameJs: '../dist/js/h5p-standalone-frame.min.js',
    frameCss: '../dist/styles/h5p.css',
    h5pContent: '../workspace/interactive-video'
});
```

This throws `TypeError: H5PIntegration.contents[("cid-" + e)] is undefined` in `
h5p-standalone-main.min.js`

I've tried leaving out the id, which only seems to work if `h5pContent` is the same.  I've also have tried using the same id, which duplicates the first declared id, regardless of the value of the h5pContent attribute.

**Comment by sdreher** [comment]
Hi - 

I've done some work with @nbuonin to track down the origin of this error. We're seeing that the `TypeError` occurs here [h5p-standalone-main.js#L12095](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L12095). The problem seems to be that the [jQuery selector here](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L12061) picks up all embedded h5ps in a page, but the global context `H5PIntegration.contents[cid-x]` may not have data for all the embedded h5ps.

For two h5p interactives embedded on a page, the sequence of events seems to be this:
1. The [$.fn.h5p](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L10930) function executes for the first interactive, which embeds the empty iFrame into the page.
2. The [$.fn.h5p](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L10930) function executes for the second interactive, which embeds a second empty iFrame into the page.
3. The async [H5PStandalone](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L10673) executes for the first interactive, which initializes the `H5PIntegration.contents['cid-0']` global context for *just* the first interactive and calls [H5P.init()](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L11768)
4. in `H5P.init`, [both iFrames are selected](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L12061).
    * The first time the loop iterates, the first interactive is initialized correctly. The `getHeadTags` function works as `H5PIntegrations.contents['cid-0']` was initialized properly in `H5PStandalone`.
    * The second time the loop iterates, the second interactive iFrame immediately gets the `h5p-initialized` class added, then throws an exception [when the H5PIntegrations.contents['cid-1'] is accessed](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L12097). This global context does not yet know about the second interactive.
5. The async [H5PStandalone](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L10673) executes for the seconds interactive, which initializes the `H5PIntegration.contents['cid-1']` and calls [H5P.init()](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L11768).
6. The [code here](https://github.com/tunapanda/h5p-standalone/blob/master/dist/js/h5p-standalone-main.js#L12061) in `H5P.init` selects 0 iFrames as both now have the `has-initialized` class.

I'll be submitting a pull request to propose one possible fix. I think there's a few ways to tackle this issue.

Thanks,
Susan

**Comment by sloopint** [comment]
Hello,
Is there anything new about this issue?
I'm working on a project including two embeds on each page, and I'm really stuck.
Thanks a lot!

**Comment by Jakeii** [comment]
Hi @sloopint please see the new readme for version 2.0.0 about multiple h5ps.
