### ISSUE TITLE
Cannot GET /workspace/H5P.GreetingCard/library.json

### ISSUE THREAD

**Issue by timothyylim** [tunapanda/h5p-standalone#4]
Hi, great job with this project. 

Unfortunately I'm still trying to figure out how it all works. I've uploaded a h5p greeting card into my workspace:

https://github.com/timothyylim/h5p-standalone/commit/eec3d55584ce3829330838968921cd61a35333b9

but am having trouble getting the content to show. Any help would be greatly appreciated.

**Comment by mgancarzdsi** [comment]
As a short workaround, rename the folder H5P.GreetingCard-1.0 to "H5P.GreetingCard" and it should start working. I believe, the versioning that came with more recent H5P libraries will be fixed in this pull request: https://github.com/tunapanda/h5p-standalone/pull/3 that @Jakeii is working on. I think if you copy the "h5p-version-in-path" it will work without having to rename things, but I haven't had a chance to try the latest changes.

**Comment by timothyylim** [comment]
It works! I'm looking forward to seeing how this repo develops.

**Comment by Jakeii** [comment]
this should be fixed as of e0be841ea9c45d3cccf877b1bca3b17fe8a6c33c

Cheers

**Comment by tamsir** [comment]
Hello
I try to do the same configuration with H5P.GoToQuestion. I rename the folder H5P.GoToQuestion-1.1 to H5P.GoToQuestion in the workspace but it don't works. Any suggestions?
Thanks
