### ISSUE TITLE
Which of the ~10mb files of the h5p ZIP are loaded?

### ISSUE THREAD

**Issue by Pr0Pennypacker** [tunapanda/h5p-standalone#80]
I unzipped a h5p file which gives me a 10mb directory, but when including it with h5p-standalone, the Firefox network analysis showed a total network traffic of 369kb (including a 200kb video) which is perfectly fine. I would like to understand under which circumstances the other files get loaded so I can calculate the required network traffic better.

**Comment by mimidotsuser** [comment]
Hello @Pr0Pennypacker,
The size might differ since H5P includes some libraries that are only required by the H5P editor.

Additionally, the H5P player first loads all the libraries' JavaScript & Stylesheet required by the content to be rendered accordingly. The required libraries are contained in the `h5p.json` located at the root folder of unzipped H5P file.

I hope you have also put into consideration the cache & content encoding when calculating the total network traffic size.
